/**
 * @fileoverview Core type definitions for the UCIL TypeScript task management fixture.
 *
 * This module defines every domain type used by the task manager, filter engine,
 * and repository.  All types use strict TypeScript — no `any`, every public
 * symbol has JSDoc.
 */

// ---------------------------------------------------------------------------
// Primitive field types
// ---------------------------------------------------------------------------

/**
 * The set of primitive TypeScript types that a task field may contain when
 * exposed through the generic filter / query layer.
 */
export type FieldType =
  | "string"
  | "number"
  | "boolean"
  | "date"
  | "null"
  | "string[]"
  | "number[]";

// ---------------------------------------------------------------------------
// Task status
// ---------------------------------------------------------------------------

/** All allowed values for {@link Task.status}. */
export const TASK_STATUS = [
  "pending",
  "in_progress",
  "done",
  "cancelled",
  "blocked",
] as const;

/** A single task status value. */
export type TaskStatus = (typeof TASK_STATUS)[number];

// ---------------------------------------------------------------------------
// Task priority
// ---------------------------------------------------------------------------

/** All allowed values for {@link Task.priority}. */
export const TASK_PRIORITY = ["low", "medium", "high", "critical"] as const;

/** A single task priority value. */
export type TaskPriority = (typeof TASK_PRIORITY)[number];

// ---------------------------------------------------------------------------
// Core Task interface
// ---------------------------------------------------------------------------

/**
 * The canonical task record stored in the repository.
 *
 * All timestamps are plain `Date` objects.  The repository never stores
 * serialised strings — callers that import/export JSON are responsible for
 * round-tripping dates through {@link parseTaskFromJSON}.
 */
export interface Task {
  /** UUID v4 string; generated by the task manager on creation. */
  id: string;
  /** Human-readable title, required, max 255 characters. */
  title: string;
  /** Extended description; may be empty string but never undefined. */
  description: string;
  /** Lifecycle status of the task. */
  status: TaskStatus;
  /** Scheduling / triage priority. */
  priority: TaskPriority;
  /** Arbitrary string labels; no duplicates enforced by the type system. */
  tags: string[];
  /** Username or user-id of the person responsible; null if unassigned. */
  assignee: string | null;
  /** Deadline; null if no deadline is set. */
  dueDate: Date | null;
  /** Immutable creation timestamp; set by the task manager. */
  createdAt: Date;
  /** Mutable last-update timestamp; refreshed on every write operation. */
  updatedAt: Date;
  /** Id of the parent task; null for root tasks. */
  parentId: string | null;
  /** Ids of direct child tasks. Maintained by the task manager. */
  subtaskIds: string[];
  /** Freeform key-value pairs for custom attributes. */
  metadata: Record<string, string | number | boolean>;
  /** Estimate of effort in hours; null if not estimated. */
  estimatedHours: number | null;
  /** Actual hours spent; null if work has not started or not tracked. */
  actualHours: number | null;
}

// ---------------------------------------------------------------------------
// Create / Update input types
// ---------------------------------------------------------------------------

/**
 * Shape of the argument passed to {@link TaskManager.createTask}.
 *
 * The `id`, `createdAt`, `updatedAt`, and `subtaskIds` fields are generated
 * automatically and must NOT be supplied by the caller.
 */
export interface CreateTaskInput {
  /** Required: human-readable title. */
  title: string;
  /** Optional description; defaults to empty string. */
  description?: string;
  /** Initial status; defaults to `"pending"`. */
  status?: TaskStatus;
  /** Initial priority; defaults to `"medium"`. */
  priority?: TaskPriority;
  /** Initial tags array; defaults to `[]`. */
  tags?: string[];
  /** Initial assignee; defaults to `null`. */
  assignee?: string | null;
  /** Optional due date. */
  dueDate?: Date | null;
  /** Id of parent task; defaults to `null`. */
  parentId?: string | null;
  /** Initial metadata key-value pairs. */
  metadata?: Record<string, string | number | boolean>;
  /** Estimated hours. */
  estimatedHours?: number | null;
  /** Actual hours. */
  actualHours?: number | null;
}

/**
 * Shape of the argument passed to {@link TaskManager.updateTask}.
 *
 * Every field is optional — only the provided fields are mutated.
 * `id`, `createdAt`, and `subtaskIds` cannot be updated via this type.
 */
export interface UpdateTaskInput {
  /** New title. */
  title?: string;
  /** New description. */
  description?: string;
  /** New status. */
  status?: TaskStatus;
  /** New priority. */
  priority?: TaskPriority;
  /** Replacement tags array (not merged). */
  tags?: string[];
  /** New assignee or null to clear. */
  assignee?: string | null;
  /** New due date or null to clear. */
  dueDate?: Date | null;
  /** New parent or null to promote to root. */
  parentId?: string | null;
  /** Replacement metadata (not merged). */
  metadata?: Record<string, string | number | boolean>;
  /** New estimated hours. */
  estimatedHours?: number | null;
  /** New actual hours. */
  actualHours?: number | null;
}

// ---------------------------------------------------------------------------
// Filter operator types
// ---------------------------------------------------------------------------

/**
 * Comparison / membership operators available in field filters.
 *
 * - `eq` / `neq`        — strict equality / inequality
 * - `lt` / `lte`        — less than / less than or equal
 * - `gt` / `gte`        — greater than / greater than or equal
 * - `contains`          — substring / array membership
 * - `startsWith`        — string prefix
 * - `endsWith`          — string suffix
 * - `in` / `notIn`      — value in / not in a list
 * - `isNull` / `isNotNull` — null-check (value argument ignored)
 */
export type FilterOperator =
  | "eq"
  | "neq"
  | "lt"
  | "lte"
  | "gt"
  | "gte"
  | "contains"
  | "startsWith"
  | "endsWith"
  | "in"
  | "notIn"
  | "isNull"
  | "isNotNull";

/**
 * Boolean connectives for composing filters into trees.
 *
 * - `and` — all child filters must be satisfied
 * - `or`  — at least one child filter must be satisfied
 * - `not` — the single child filter must NOT be satisfied (logical negation)
 */
export type LogicalOperator = "and" | "or" | "not";

// ---------------------------------------------------------------------------
// Filter node types
// ---------------------------------------------------------------------------

/**
 * A leaf filter that tests a single task field against a value using an
 * operator.
 *
 * @example
 * ```typescript
 * const f: FieldFilter = { field: "status", operator: "eq", value: "pending" };
 * ```
 */
export interface FieldFilter {
  /** The task field name (or dot-path for metadata sub-fields). */
  field: keyof Task | string;
  /** The comparison or membership operator to apply. */
  operator: FilterOperator;
  /**
   * The right-hand side value.  Must be compatible with the field type and
   * operator; the filter engine throws {@link QueryError} for mismatches.
   */
  value: unknown;
}

/**
 * A branch node that combines child filters with a boolean connective.
 *
 * @example
 * ```typescript
 * const f: LogicalFilter = {
 *   operator: "and",
 *   filters: [
 *     { field: "status", operator: "eq", value: "pending" },
 *     { field: "priority", operator: "gte", value: "high" },
 *   ],
 * };
 * ```
 */
export interface LogicalFilter {
  /** Boolean connective. */
  operator: LogicalOperator;
  /** Child filters.  For `not`, exactly one element is expected. */
  filters: Filter[];
}

/** A filter is either a leaf field check or a logical combinator. */
export type Filter = FieldFilter | LogicalFilter;

// ---------------------------------------------------------------------------
// Sort specification types
// ---------------------------------------------------------------------------

/** Direction of ordering for a sort key. */
export type SortDirection = "asc" | "desc";

/**
 * A single sort key with direction and null-placement policy.
 *
 * @example
 * ```typescript
 * const sort: SortSpec = { field: "priority", direction: "desc", nulls: "last" };
 * ```
 */
export interface SortSpec {
  /** Task field to sort by. */
  field: keyof Task | string;
  /** Sort direction. */
  direction: SortDirection;
  /**
   * Where to place null values relative to non-null values.
   * Defaults to `"last"` when not specified.
   */
  nulls?: "first" | "last";
}

// ---------------------------------------------------------------------------
// Query type
// ---------------------------------------------------------------------------

/**
 * A full query descriptor accepted by {@link TaskManager.query} and
 * {@link FilterEngine.applyQuery}.
 *
 * @example
 * ```typescript
 * const q: Query = {
 *   filter: { field: "status", operator: "eq", value: "pending" },
 *   sort: [{ field: "priority", direction: "desc" }],
 *   limit: 10,
 *   offset: 0,
 * };
 * ```
 */
export interface Query {
  /** Optional filter tree to restrict results. */
  filter?: Filter;
  /** Ordered list of sort keys; ties broken left-to-right. */
  sort?: SortSpec[];
  /** Maximum number of results to return (page size). */
  limit?: number;
  /** Zero-based index of the first result to return (for pagination). */
  offset?: number;
  /** If provided, only these task fields are projected into the result items. */
  fields?: Array<keyof Task>;
}

// ---------------------------------------------------------------------------
// Result types
// ---------------------------------------------------------------------------

/**
 * A paginated result set from a query operation.
 *
 * @template T — normally {@link Task} but may be a partial projection.
 */
export interface QueryResult<T = Task> {
  /** The matching items for the current page. */
  items: T[];
  /** Total number of items matching the filter (ignoring limit/offset). */
  total: number;
  /** Whether there are more items beyond the current page. */
  hasMore: boolean;
  /** The offset that was used to produce this page. */
  offset: number;
  /** The limit that was used to produce this page (may differ from requested). */
  limit: number;
}

/**
 * The result of an aggregate computation over a filtered task set.
 *
 * Each numeric field in `sum`, `avg`, `min`, `max` is keyed by field name.
 */
export interface AggregateResult {
  /** Number of tasks in this aggregate bucket. */
  count: number;
  /** Sum of numeric fields; present when requested. */
  sum?: Record<string, number>;
  /** Average of numeric fields; present when requested. */
  avg?: Record<string, number>;
  /** Minimum of numeric/date fields; present when requested. */
  min?: Record<string, number | Date>;
  /** Maximum of numeric/date fields; present when requested. */
  max?: Record<string, number | Date>;
  /**
   * When a `groupBy` was performed, each group key maps to a nested result.
   */
  groupBy?: Record<string, AggregateResult>;
}

// ---------------------------------------------------------------------------
// Event types
// ---------------------------------------------------------------------------

/** The set of lifecycle events emitted by the task manager. */
export type TaskEventType =
  | "created"
  | "updated"
  | "deleted"
  | "statusChanged"
  | "priorityChanged"
  | "assigned";

/**
 * An immutable snapshot of a task lifecycle event.
 *
 * Listeners registered via {@link TaskManager.on} receive instances of this
 * type.
 */
export interface TaskEvent {
  /** The kind of lifecycle transition that occurred. */
  type: TaskEventType;
  /** Id of the task that was affected. */
  taskId: string;
  /** Wall-clock timestamp when the event was emitted. */
  timestamp: Date;
  /** The field value before the change (for update / transition events). */
  previousValue?: unknown;
  /** The field value after the change. */
  newValue?: unknown;
  /** Optional user id of whoever triggered the change. */
  userId?: string;
}

// ---------------------------------------------------------------------------
// Error types
// ---------------------------------------------------------------------------

/**
 * Thrown when an operation targets a task id that does not exist in the
 * repository.
 */
export class TaskNotFoundError extends Error {
  /** The missing task id. */
  public readonly taskId: string;

  /**
   * @param taskId — The id that was looked up unsuccessfully.
   */
  constructor(taskId: string) {
    super(`Task not found: ${taskId}`);
    this.name = "TaskNotFoundError";
    this.taskId = taskId;
  }
}

/**
 * Thrown when a {@link CreateTaskInput} or {@link UpdateTaskInput} violates a
 * domain constraint (e.g. title is empty, estimatedHours is negative).
 */
export class ValidationError extends Error {
  /** The field that caused the validation failure. */
  public readonly field: string;
  /** The invalid value. */
  public readonly invalidValue: unknown;

  /**
   * @param field        — Name of the offending field.
   * @param invalidValue — The value that triggered the error.
   * @param message      — Human-readable explanation.
   */
  constructor(field: string, invalidValue: unknown, message: string) {
    super(message);
    this.name = "ValidationError";
    this.field = field;
    this.invalidValue = invalidValue;
  }
}

/**
 * Thrown when a {@link Query} or {@link Filter} is structurally invalid (e.g.
 * unknown operator, incompatible type for field).
 */
export class QueryError extends Error {
  /** The expression or fragment that failed to parse / execute. */
  public readonly expression: string;

  /**
   * @param expression — The raw expression string or a stringified filter node.
   * @param message    — Human-readable explanation.
   */
  constructor(expression: string, message: string) {
    super(message);
    this.name = "QueryError";
    this.expression = expression;
  }
}

// ---------------------------------------------------------------------------
// Type guards
// ---------------------------------------------------------------------------

/**
 * Returns `true` when `value` is a non-null plain object (not an array).
 * Used as a precondition check throughout the filter engine and repository.
 */
export function isPlainObject(value: unknown): value is Record<string, unknown> {
  return (
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    Object.getPrototypeOf(value) === Object.prototype
  );
}

/**
 * Returns `true` when `value` is a valid {@link TaskStatus} string.
 */
export function isTaskStatus(value: unknown): value is TaskStatus {
  return (
    typeof value === "string" &&
    (TASK_STATUS as ReadonlyArray<string>).includes(value)
  );
}

/**
 * Returns `true` when `value` is a valid {@link TaskPriority} string.
 */
export function isTaskPriority(value: unknown): value is TaskPriority {
  return (
    typeof value === "string" &&
    (TASK_PRIORITY as ReadonlyArray<string>).includes(value)
  );
}

/**
 * Returns `true` when `value` conforms to the full {@link Task} interface.
 *
 * This is a shallow structural check — it does not recursively validate
 * every metadata entry.
 */
export function isTask(value: unknown): value is Task {
  if (!isPlainObject(value)) return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v["id"] === "string" &&
    typeof v["title"] === "string" &&
    typeof v["description"] === "string" &&
    isTaskStatus(v["status"]) &&
    isTaskPriority(v["priority"]) &&
    Array.isArray(v["tags"]) &&
    (v["assignee"] === null || typeof v["assignee"] === "string") &&
    (v["dueDate"] === null || v["dueDate"] instanceof Date) &&
    v["createdAt"] instanceof Date &&
    v["updatedAt"] instanceof Date &&
    (v["parentId"] === null || typeof v["parentId"] === "string") &&
    Array.isArray(v["subtaskIds"]) &&
    isPlainObject(v["metadata"]) &&
    (v["estimatedHours"] === null || typeof v["estimatedHours"] === "number") &&
    (v["actualHours"] === null || typeof v["actualHours"] === "number")
  );
}

/**
 * Returns `true` when `value` is a {@link FieldFilter} (leaf node).
 */
export function isFieldFilter(value: unknown): value is FieldFilter {
  if (!isPlainObject(value)) return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v["field"] === "string" &&
    typeof v["operator"] === "string" &&
    isFilterOperator(v["operator"]) &&
    "value" in v
  );
}

/**
 * Returns `true` when `value` is a {@link LogicalFilter} (branch node).
 */
export function isLogicalFilter(value: unknown): value is LogicalFilter {
  if (!isPlainObject(value)) return false;
  const v = value as Record<string, unknown>;
  return (
    typeof v["operator"] === "string" &&
    isLogicalOperator(v["operator"]) &&
    Array.isArray(v["filters"])
  );
}

/**
 * Returns `true` when `value` is either a {@link FieldFilter} or a
 * {@link LogicalFilter}.
 */
export function isFilter(value: unknown): value is Filter {
  return isFieldFilter(value) || isLogicalFilter(value);
}

/** Returns `true` when `s` is a valid {@link FilterOperator}. */
export function isFilterOperator(s: string): s is FilterOperator {
  const ops: FilterOperator[] = [
    "eq",
    "neq",
    "lt",
    "lte",
    "gt",
    "gte",
    "contains",
    "startsWith",
    "endsWith",
    "in",
    "notIn",
    "isNull",
    "isNotNull",
  ];
  return (ops as string[]).includes(s);
}

/** Returns `true` when `s` is a valid {@link LogicalOperator}. */
export function isLogicalOperator(s: string): s is LogicalOperator {
  return s === "and" || s === "or" || s === "not";
}

/** Returns `true` when `s` is a valid {@link SortDirection}. */
export function isSortDirection(s: string): s is SortDirection {
  return s === "asc" || s === "desc";
}

/** Returns `true` when `s` is a valid {@link TaskEventType}. */
export function isTaskEventType(s: string): s is TaskEventType {
  const types: TaskEventType[] = [
    "created",
    "updated",
    "deleted",
    "statusChanged",
    "priorityChanged",
    "assigned",
  ];
  return (types as string[]).includes(s);
}

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

/**
 * Validates that `value` is a known {@link TaskStatus}; throws
 * {@link ValidationError} otherwise.
 *
 * @param value — The candidate value.
 * @returns The validated status.
 */
export function validateTaskStatus(value: unknown): TaskStatus {
  if (!isTaskStatus(value)) {
    throw new ValidationError(
      "status",
      value,
      `Invalid status "${String(value)}". Must be one of: ${TASK_STATUS.join(", ")}.`
    );
  }
  return value;
}

/**
 * Validates that `value` is a known {@link TaskPriority}; throws
 * {@link ValidationError} otherwise.
 *
 * @param value — The candidate value.
 * @returns The validated priority.
 */
export function validatePriority(value: unknown): TaskPriority {
  if (!isTaskPriority(value)) {
    throw new ValidationError(
      "priority",
      value,
      `Invalid priority "${String(value)}". Must be one of: ${TASK_PRIORITY.join(", ")}.`
    );
  }
  return value;
}

/**
 * Validates a task title: non-empty string, max 255 characters.
 *
 * @param value — The candidate title.
 * @returns The trimmed, validated title.
 */
export function validateTitle(value: unknown): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new ValidationError(
      "title",
      value,
      "Task title must be a non-empty string."
    );
  }
  const trimmed = value.trim();
  if (trimmed.length > 255) {
    throw new ValidationError(
      "title",
      value,
      `Task title exceeds maximum length of 255 characters (got ${trimmed.length}).`
    );
  }
  return trimmed;
}

/**
 * Validates an optional numeric hours field (must be non-negative when
 * provided).
 *
 * @param value — The candidate number of hours.
 * @param field — Field name for error messages.
 * @returns The validated number, or `null`.
 */
export function validateHours(value: unknown, field: string): number | null {
  if (value === null || value === undefined) return null;
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0) {
    throw new ValidationError(
      field,
      value,
      `${field} must be a non-negative finite number.`
    );
  }
  return value;
}

/**
 * Validates that `tags` is an array of non-empty strings.
 *
 * @param tags — Candidate tag array.
 * @returns The validated tags array.
 */
export function validateTags(tags: unknown): string[] {
  if (!Array.isArray(tags)) {
    throw new ValidationError("tags", tags, "tags must be an array of strings.");
  }
  for (const tag of tags) {
    if (typeof tag !== "string" || tag.trim().length === 0) {
      throw new ValidationError(
        "tags",
        tag,
        `Each tag must be a non-empty string; got ${JSON.stringify(tag)}.`
      );
    }
  }
  return tags as string[];
}

/**
 * Validates that `metadata` is a plain object whose values are all strings,
 * numbers, or booleans.
 *
 * @param metadata — Candidate metadata object.
 * @returns The validated metadata.
 */
export function validateMetadata(
  metadata: unknown
): Record<string, string | number | boolean> {
  if (!isPlainObject(metadata)) {
    throw new ValidationError(
      "metadata",
      metadata,
      "metadata must be a plain object."
    );
  }
  for (const [key, val] of Object.entries(metadata)) {
    if (
      typeof val !== "string" &&
      typeof val !== "number" &&
      typeof val !== "boolean"
    ) {
      throw new ValidationError(
        `metadata.${key}`,
        val,
        `metadata values must be string, number, or boolean; field "${key}" has type ${typeof val}.`
      );
    }
  }
  return metadata as Record<string, string | number | boolean>;
}

// ---------------------------------------------------------------------------
// Serialisation helpers
// ---------------------------------------------------------------------------

/**
 * A JSON-serialisable representation of a {@link Task} where all `Date`
 * fields are replaced with ISO-8601 strings.
 */
export interface SerializedTask {
  id: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  tags: string[];
  assignee: string | null;
  dueDate: string | null;
  createdAt: string;
  updatedAt: string;
  parentId: string | null;
  subtaskIds: string[];
  metadata: Record<string, string | number | boolean>;
  estimatedHours: number | null;
  actualHours: number | null;
}

/**
 * Converts a live {@link Task} to a JSON-safe {@link SerializedTask}.
 *
 * @param task — The task to serialise.
 * @returns A plain object suitable for `JSON.stringify`.
 */
export function serializeTask(task: Task): SerializedTask {
  return {
    id: task.id,
    title: task.title,
    description: task.description,
    status: task.status,
    priority: task.priority,
    tags: [...task.tags],
    assignee: task.assignee,
    dueDate: task.dueDate !== null ? task.dueDate.toISOString() : null,
    createdAt: task.createdAt.toISOString(),
    updatedAt: task.updatedAt.toISOString(),
    parentId: task.parentId,
    subtaskIds: [...task.subtaskIds],
    metadata: { ...task.metadata },
    estimatedHours: task.estimatedHours,
    actualHours: task.actualHours,
  };
}

/**
 * Parses a raw JSON object (from `JSON.parse`) back into a live {@link Task}.
 *
 * @param raw — A plain object that should conform to {@link SerializedTask}.
 * @returns A fully hydrated `Task`.
 * @throws {@link ValidationError} when required fields are missing or malformed.
 */
export function parseTaskFromJSON(raw: unknown): Task {
  if (!isPlainObject(raw)) {
    throw new ValidationError("(root)", raw, "Expected a plain object.");
  }
  const r = raw as Record<string, unknown>;

  const id = typeof r["id"] === "string" ? r["id"] : undefined;
  if (id === undefined) {
    throw new ValidationError("id", r["id"], "Task id must be a string.");
  }

  const title = validateTitle(r["title"]);
  const description =
    typeof r["description"] === "string" ? r["description"] : "";
  const status = validateTaskStatus(r["status"]);
  const priority = validatePriority(r["priority"]);
  const tags = Array.isArray(r["tags"]) ? validateTags(r["tags"]) : [];
  const assignee =
    r["assignee"] === null || typeof r["assignee"] === "string"
      ? (r["assignee"] as string | null)
      : null;
  const dueDate =
    r["dueDate"] === null || r["dueDate"] === undefined
      ? null
      : new Date(r["dueDate"] as string);
  const createdAt =
    r["createdAt"] !== undefined
      ? new Date(r["createdAt"] as string)
      : new Date();
  const updatedAt =
    r["updatedAt"] !== undefined
      ? new Date(r["updatedAt"] as string)
      : new Date();
  const parentId =
    r["parentId"] === null || typeof r["parentId"] === "string"
      ? (r["parentId"] as string | null)
      : null;
  const subtaskIds = Array.isArray(r["subtaskIds"])
    ? (r["subtaskIds"] as string[])
    : [];
  const metadata = isPlainObject(r["metadata"])
    ? validateMetadata(r["metadata"])
    : {};
  const estimatedHours = validateHours(r["estimatedHours"] ?? null, "estimatedHours");
  const actualHours = validateHours(r["actualHours"] ?? null, "actualHours");

  return {
    id,
    title,
    description,
    status,
    priority,
    tags,
    assignee,
    dueDate,
    createdAt,
    updatedAt,
    parentId,
    subtaskIds,
    metadata,
    estimatedHours,
    actualHours,
  };
}

// ---------------------------------------------------------------------------
// Priority ordering helpers
// ---------------------------------------------------------------------------

/** Numeric weight of each priority for comparison purposes (higher = more urgent). */
export const PRIORITY_WEIGHT: Record<TaskPriority, number> = {
  low: 1,
  medium: 2,
  high: 3,
  critical: 4,
};

/**
 * Compares two priorities by their urgency weight.
 *
 * @returns A negative number when `a` < `b`, 0 when equal, positive when `a` > `b`.
 */
export function comparePriority(a: TaskPriority, b: TaskPriority): number {
  return PRIORITY_WEIGHT[a] - PRIORITY_WEIGHT[b];
}

// ---------------------------------------------------------------------------
// Status transition helpers
// ---------------------------------------------------------------------------

/**
 * Returns `true` when a task may transition from `from` to `to` under the
 * default state machine rules.
 *
 * The allowed transitions are:
 *
 * ```
 * pending     → in_progress, cancelled, blocked
 * in_progress → done, cancelled, blocked, pending
 * blocked     → in_progress, cancelled, pending
 * done        → (terminal — no transitions allowed)
 * cancelled   → (terminal — no transitions allowed)
 * ```
 */
export function isValidStatusTransition(
  from: TaskStatus,
  to: TaskStatus
): boolean {
  if (from === to) return true;
  const ALLOWED: Record<TaskStatus, TaskStatus[]> = {
    pending: ["in_progress", "cancelled", "blocked"],
    in_progress: ["done", "cancelled", "blocked", "pending"],
    blocked: ["in_progress", "cancelled", "pending"],
    done: [],
    cancelled: [],
  };
  return ALLOWED[from].includes(to);
}

// ---------------------------------------------------------------------------
// Utility: deep-clone a Task
// ---------------------------------------------------------------------------

/**
 * Returns a deep clone of `task` such that no reference is shared with the
 * original.  Arrays, Dates, and the metadata record are all copied.
 *
 * @param task — The task to clone.
 * @returns A completely independent copy.
 */
export function cloneTask(task: Task): Task {
  return {
    id: task.id,
    title: task.title,
    description: task.description,
    status: task.status,
    priority: task.priority,
    tags: [...task.tags],
    assignee: task.assignee,
    dueDate: task.dueDate !== null ? new Date(task.dueDate.getTime()) : null,
    createdAt: new Date(task.createdAt.getTime()),
    updatedAt: new Date(task.updatedAt.getTime()),
    parentId: task.parentId,
    subtaskIds: [...task.subtaskIds],
    metadata: { ...task.metadata },
    estimatedHours: task.estimatedHours,
    actualHours: task.actualHours,
  };
}

// ---------------------------------------------------------------------------
// Utility: partial task projection
// ---------------------------------------------------------------------------

/**
 * Projects a full {@link Task} onto only the fields listed in `fields`.
 *
 * @param task   — Source task.
 * @param fields — Field names to include.
 * @returns A partial task record.
 */
export function projectTask(
  task: Task,
  fields: Array<keyof Task>
): Partial<Task> {
  const result: Partial<Task> = {};
  for (const field of fields) {
    // Use type assertion for dynamic property assignment; the cast is safe
    // because `fields` is constrained to `keyof Task`.
    (result as Record<string, unknown>)[field] = task[field];
  }
  return result;
}

// ---------------------------------------------------------------------------
// Overdue helper
// ---------------------------------------------------------------------------

/**
 * Returns `true` when `task` has a `dueDate` in the past and is not yet in a
 * terminal status (`done` or `cancelled`).
 *
 * @param task — The task to evaluate.
 * @param now  — Reference time; defaults to `new Date()`.
 */
export function isOverdue(task: Task, now: Date = new Date()): boolean {
  if (task.dueDate === null) return false;
  if (task.status === "done" || task.status === "cancelled") return false;
  return task.dueDate.getTime() < now.getTime();
}

// ---------------------------------------------------------------------------
// ID generation helper (no external dependency)
// ---------------------------------------------------------------------------

/**
 * Generates a pseudo-random UUID v4 string using the Web Crypto API available
 * in Node 20+.
 *
 * @returns A UUID v4 string such as `"550e8400-e29b-41d4-a716-446655440000"`.
 */
export function generateId(): string {
  // crypto.randomUUID() is available in Node 19+ and all modern browsers.
  return crypto.randomUUID();
}

// ---------------------------------------------------------------------------
// Snapshot type for transactions
// ---------------------------------------------------------------------------

/**
 * An immutable snapshot of repository state, used by the transaction layer.
 *
 * Stored as a `Map` from task id to a deep-cloned `Task` so that restore is
 * O(n) and does not require a full serialisation round-trip.
 */
export type RepositorySnapshot = Map<string, Task>;

// ---------------------------------------------------------------------------
// Statistics type
// ---------------------------------------------------------------------------

/**
 * A summary of the current state of all tasks in the repository.
 */
export interface TaskStats {
  /** Total number of tasks. */
  total: number;
  /** Count per status. */
  byStatus: Record<TaskStatus, number>;
  /** Count per priority. */
  byPriority: Record<TaskPriority, number>;
  /** Number of tasks whose `dueDate` is in the past and status is not terminal. */
  overdue: number;
}

// ---------------------------------------------------------------------------
// Filter expression AST (used by FilterExpressionParser)
// ---------------------------------------------------------------------------

/**
 * Token kinds emitted by the expression lexer.
 * @internal
 */
export type TokenKind =
  | "IDENT"
  | "STRING"
  | "NUMBER"
  | "BOOLEAN"
  | "NULL"
  | "LPAREN"
  | "RPAREN"
  | "COMMA"
  | "AND"
  | "OR"
  | "NOT"
  | "IS"
  | "IN"
  | "CONTAINS"
  | "STARTS_WITH"
  | "ENDS_WITH"
  | "EQ"
  | "NEQ"
  | "LT"
  | "LTE"
  | "GT"
  | "GTE"
  | "EOF";

/**
 * A single token produced by the expression lexer.
 * @internal
 */
export interface Token {
  kind: TokenKind;
  value: string;
  /** Zero-based offset in the source string. */
  offset: number;
}

// ---------------------------------------------------------------------------
// Export collection re-export for convenience
// ---------------------------------------------------------------------------

/** All status values as a plain mutable array (for iteration). */
export const ALL_STATUSES: TaskStatus[] = [...TASK_STATUS];

/** All priority values as a plain mutable array (for iteration). */
export const ALL_PRIORITIES: TaskPriority[] = [...TASK_PRIORITY];

/** All filter operators as a plain array. */
export const ALL_FILTER_OPERATORS: FilterOperator[] = [
  "eq",
  "neq",
  "lt",
  "lte",
  "gt",
  "gte",
  "contains",
  "startsWith",
  "endsWith",
  "in",
  "notIn",
  "isNull",
  "isNotNull",
];

/** All logical operators as a plain array. */
export const ALL_LOGICAL_OPERATORS: LogicalOperator[] = ["and", "or", "not"];

/** All task event types as a plain array. */
export const ALL_EVENT_TYPES: TaskEventType[] = [
  "created",
  "updated",
  "deleted",
  "statusChanged",
  "priorityChanged",
  "assigned",
];

/** Maximum allowed title length in characters. */
export const MAX_TITLE_LENGTH = 255;

/** Default page size when a query does not specify a limit. */
export const DEFAULT_QUERY_LIMIT = 50;

/** Hard cap on the number of items returnable in one page. */
export const MAX_QUERY_LIMIT = 1000;
